Add 鈍音 and 銳音
nk2028/qieyun-js pull request #24
Opened 2022-03-24 23:18 UTC by graphemecluster

鋭

2022-03-25 02:38 UTC, syimyuzya requested changes
doc 需要說明一下「鈍音」「銳音」分別指什麼

【雖然多數人可能都知道兩者指的是脣牙喉（以母除外）聲母和其他聲母，但也最好明顯出現在 doc 裡

2022-03-25 02:50 UTC, graphemecluster commented
@syimyuzya 忘了改 doc 😓
那麼 doc 其餘的表達式是不是也應該要解釋一下，直接寫在這兒篇幅會不會太長呢？

2022-03-25 02:56 UTC, syimyuzya commented
> @syimyuzya 忘了改 doc sweat 那麼 doc 其餘的表達式是不是也應該要解釋一下，直接寫在這兒篇幅會不會太長呢？

其實……是應該都寫的😂 比如「喉音」和「影組」是否等價（包不包含以母）啊、曉母是「全清」還是「次清」啊什麼的；不過這些都可以另開個 issue 了w

2022-03-26 11:03 UTC, syimyuzya approved these changes

2022-03-27 16:27 UTC, merged